// Code generated by templ@v0.2.364 DO NOT EDIT.

package main

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func about() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_1 := templ.GetChildren(ctx)
		if var_1 == nil {
			var_1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, err = templBuffer.WriteString("<div class=\"mx-auto sm:w-4/5 max-w-5xl px-4 sm:px-6 lg:px-8\"><div class=\"w-full text-center py-6\"><div class=\"text-3xl text-center font-semibold\">")
		if err != nil {
			return err
		}
		var_2 := `Introduction`
		_, err = templBuffer.WriteString(var_2)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</div><div class=\"border border-black p-4 shadow-md rounded-lg\"><div class=\"w-full text-center py-2\"><p class=\"italic text-gray-600\">")
		if err != nil {
			return err
		}
		var_3 := `(As a Kiwi, this level of self-promotion makes me deeply uncomfortable, but here we go...)`
		_, err = templBuffer.WriteString(var_3)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</p></div><p class=\"mb-4 text-gray-700\">")
		if err != nil {
			return err
		}
		var_4 := `I have been developing in a professional capacity as a full stack developer for over 10 years.`
		_, err = templBuffer.WriteString(var_4)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</p><p class=\"mb-4 text-gray-700\">")
		if err != nil {
			return err
		}
		var_5 := `I have extensive experience in implementing complex software solutions, based on varying degrees of specification.`
		_, err = templBuffer.WriteString(var_5)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</p><p class=\"mb-4 text-gray-700\">")
		if err != nil {
			return err
		}
		var_6 := `Working closely with stakeholders, refining and architecting solutions through to deployment, maintenance and support.`
		_, err = templBuffer.WriteString(var_6)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</p><p class=\"mb-4 text-gray-700\">")
		if err != nil {
			return err
		}
		var_7 := `I am passionate about solving real problems, working with the best tools (or getting there) and improving the overall effectiveness of the organisation and the team`
		_, err = templBuffer.WriteString(var_7)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</p><p class=\"mb-4 text-gray-700\">")
		if err != nil {
			return err
		}
		var_8 := `I am excited about continuing to explore the benefits and opportunities of serverless/cloud solutions.`
		_, err = templBuffer.WriteString(var_8)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</p><div class=\"text-center w-full\"><a class=\"underline text-2xl hover:text-blue-500 font-semibold\" href=\"mailto:ghcumming01@gmail.com\">")
		if err != nil {
			return err
		}
		var_9 := `Get in touch`
		_, err = templBuffer.WriteString(var_9)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</a></div></div></div><div class=\"w-full\"><div style=\"width: 800px;\" class=\"m-auto\"><div class=\"text-3xl text-center font-semibold mb-4\">")
		if err != nil {
			return err
		}
		var_10 := `Flying Drones FPV`
		_, err = templBuffer.WriteString(var_10)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</div><div class=\"border border-black p-4 shadow-lg rounded-lg bg-white\"><div class=\"text-center font-medium text-gray-800\">")
		if err != nil {
			return err
		}
		var_11 := `I love building and flying First-Person-View Quadcopters.`
		_, err = templBuffer.WriteString(var_11)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</div><div class=\"text-center font-medium text-gray-800\">")
		if err != nil {
			return err
		}
		var_12 := `(The photo of me at the top is after clambering up that mountain to retrieve a lost quad!)`
		_, err = templBuffer.WriteString(var_12)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</div><!--")
		if err != nil {
			return err
		}
		var_13 := ` Image and Iframe content here `
		_, err = templBuffer.WriteString(var_13)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("--><div class=\"italic text-center text-gray-600\">")
		if err != nil {
			return err
		}
		var_14 := `Watch out for YouTube compression here!`
		_, err = templBuffer.WriteString(var_14)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</div><div class=\"text-xl text-center font-medium text-gray-800\">")
		if err != nil {
			return err
		}
		var_15 := `something more scenic....`
		_, err = templBuffer.WriteString(var_15)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</div><div style=\"width: 800px;\" class=\"m-auto\"><div style=\"width: 800px; height: 360px;\"><div style=\"width: 100%; height: 100%;\"><iframe allowfullscreen=\"\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" title=\"Measured Manoeuvres\" src=\"https://www.youtube.com/embed/fxbgoZZdHD4?autoplay=0&amp;mute=0&amp;controls=0&amp;origin=https%3A%2F%2Fgregc.dev&amp;playsinline=1&amp;showinfo=0&amp;rel=0&amp;iv_load_policy=3&amp;modestbranding=true&amp;loop=1&amp;enablejsapi=1&amp;widgetid=1\" id=\"widget2\" width=\"100%\" height=\"100%\" frameborder=\"0\"></iframe></div></div></div></div></div></div></div>")
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}
