// Code generated by templ@v0.2.364 DO NOT EDIT.

package main

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func nzcovidmap() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_1 := templ.GetChildren(ctx)
		if var_1 == nil {
			var_1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var_2 := templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
			templBuffer, templIsBuffer := w.(*bytes.Buffer)
			if !templIsBuffer {
				templBuffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templBuffer)
			}
			_, err = templBuffer.WriteString("<div><img src=\"./img/covid19/icon-512x512.webp\" alt=\"Locations of Interest Explorer Icon\" class=\"h-16 w-16 md:h-24 md:w-24 mx-auto\"><p>")
			if err != nil {
				return err
			}
			var_3 := `Over the course of the pandemic, the NZCovidMap reached over 200,000 Kiwis across New Zealand, with a peak of 15,000 daily unique visitors. This tool provided people with a mobile-friendly view of Covid-19 Locations of Interest published by the NZ Ministry of Health. `
			_, err = templBuffer.WriteString(var_3)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</p><ul><li>")
			if err != nil {
				return err
			}
			var_4 := `- Circle-based location selection method`
			_, err = templBuffer.WriteString(var_4)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</li><li>")
			if err != nil {
				return err
			}
			var_5 := `A Mobile-friendly map view for digesting localized information`
			_, err = templBuffer.WriteString(var_5)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</li><li>")
			if err != nil {
				return err
			}
			var_6 := `- Location specific url pathing query params + "share link to location"`
			_, err = templBuffer.WriteString(var_6)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</li><li>")
			if err != nil {
				return err
			}
			var_7 := `- Generation of location-specific meta screenshots for engaging social media preview images.`
			_, err = templBuffer.WriteString(var_7)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</li><li>")
			if err != nil {
				return err
			}
			var_8 := `Reddit Integration - Auto-Generate a "Location of Interest summary" for each subreddit & share relevant subreddit`
			_, err = templBuffer.WriteString(var_8)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</li></ul></div> <div class=\"flex justify-center\"><img class=\"rounded-lg shadow-lg\" src=\"./img/covid19/covid_desktop.webp\" alt=\"NZCovidMap Screenshot\"></div> ")
			if err != nil {
				return err
			}
			var_9 := templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
				templBuffer, templIsBuffer := w.(*bytes.Buffer)
				if !templIsBuffer {
					templBuffer = templ.GetBuffer()
					defer templ.ReleaseBuffer(templBuffer)
				}
				_, err = templBuffer.WriteString("<p>")
				if err != nil {
					return err
				}
				var_10 := `Each hour, the application would check for new locations in specific communities and (if a sub-reddit exists) posts for any new locations in a standard post format.`
				_, err = templBuffer.WriteString(var_10)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</p> <img src=\"./img/covid19/covid-reddit.png\" class=\"rounded-lg shadow-lg\" height=\"800px\">")
				if err != nil {
					return err
				}
				if !templIsBuffer {
					_, err = io.Copy(w, templBuffer)
				}
				return err
			})
			err = subbox("Auto updates").Render(templ.WithChildren(ctx, var_9), templBuffer)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString(" ")
			if err != nil {
				return err
			}
			var_11 := templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
				templBuffer, templIsBuffer := w.(*bytes.Buffer)
				if !templIsBuffer {
					templBuffer = templ.GetBuffer()
					defer templ.ReleaseBuffer(templBuffer)
				}
				_, err = templBuffer.WriteString("<div class=\"flex\"><div><ul class=\"list-inside list-disc\"><li>")
				if err != nil {
					return err
				}
				var_12 := `Provide a Mobile-friendly view of Locations of Interest`
				_, err = templBuffer.WriteString(var_12)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</li><li>")
				if err != nil {
					return err
				}
				var_13 := `Raise awareness of Locations of Interests in our community.`
				_, err = templBuffer.WriteString(var_13)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</li><li>")
				if err != nil {
					return err
				}
				var_14 := `Lower anxiety for those seeking updates about their community.`
				_, err = templBuffer.WriteString(var_14)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</li></ul><h1>")
				if err != nil {
					return err
				}
				var_15 := `Tech`
				_, err = templBuffer.WriteString(var_15)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</h1><ul class=\"list-inside list-disc\"><li>")
				if err != nil {
					return err
				}
				var_16 := `Up-to-date social Media sharing icons created for each town/city`
				_, err = templBuffer.WriteString(var_16)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</li></ul>")
				if err != nil {
					return err
				}
				var_17 := templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
					templBuffer, templIsBuffer := w.(*bytes.Buffer)
					if !templIsBuffer {
						templBuffer = templ.GetBuffer()
						defer templ.ReleaseBuffer(templBuffer)
					}
					_, err = templBuffer.WriteString("<ul class=\"list-inside list-disc\"><li>")
					if err != nil {
						return err
					}
					var_18 := `An n8n workflow that reads the CSV file published by the MoH. Locations are then categorized and saved.`
					_, err = templBuffer.WriteString(var_18)
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("</li><li>")
					if err != nil {
						return err
					}
					var_19 := `An n8n workflow endpoint that returns all the locations in the last 30 days.`
					_, err = templBuffer.WriteString(var_19)
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("</li><li>")
					if err != nil {
						return err
					}
					var_20 := `A statically rendered Next.JS site that is published each hour. A mobile-friendly interactive map with all locations marked.`
					_, err = templBuffer.WriteString(var_20)
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("</li><li>")
					if err != nil {
						return err
					}
					var_21 := `A hourly job to build sub-reddit content and sent updates to places with new/updated Locations of Interest.`
					_, err = templBuffer.WriteString(var_21)
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("</li></ul> <h1>")
					if err != nil {
						return err
					}
					var_22 := `Why so complex?`
					_, err = templBuffer.WriteString(var_22)
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("</h1> <ul class=\"list-inside list-disc\"><p>")
					if err != nil {
						return err
					}
					var_23 := `To reduce the complexity, cost and on-going maintenance cost of the application, we removed the n8n workflow the Next.JS site build on and replaced it with direct calls to the MoH API.`
					_, err = templBuffer.WriteString(var_23)
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("</p><p>")
					if err != nil {
						return err
					}
					var_24 := `This allowed the site to be fully independent of my own local infustructure and for its whole lifetime, run entirely for free on Vercel`
					_, err = templBuffer.WriteString(var_24)
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("</p></ul>")
					if err != nil {
						return err
					}
					if !templIsBuffer {
						_, err = io.Copy(w, templBuffer)
					}
					return err
				})
				err = subbox("Design").Render(templ.WithChildren(ctx, var_17), templBuffer)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</div><img src=\"./img/covid19/nzcovid_2.webp\" class=\"rounded-lg shadow-lg\" height=\"800px\"></div>")
				if err != nil {
					return err
				}
				if !templIsBuffer {
					_, err = io.Copy(w, templBuffer)
				}
				return err
			})
			err = subbox("Goals").Render(templ.WithChildren(ctx, var_11), templBuffer)
			if err != nil {
				return err
			}
			if !templIsBuffer {
				_, err = io.Copy(w, templBuffer)
			}
			return err
		})
		err = box("NZCovidMap", "nzcovidmap", false).Render(templ.WithChildren(ctx, var_2), templBuffer)
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}
