// Code generated by templ@v0.2.364 DO NOT EDIT.

package main

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func nzcovidmap() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_1 := templ.GetChildren(ctx)
		if var_1 == nil {
			var_1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, err = templBuffer.WriteString("<div><div class=\"text-left flex items-center justify-center h-screen gap-2 p-5 text-center font-medium font-mono grid grid-cols-1 md:grid-cols-2 lg:grid-cols-2\"><div class=\"font-bold rounded-lg border shadow-lg p-10\"><h1 class=\"text-4xl font-medium p-5\">")
		if err != nil {
			return err
		}
		var_2 := `NZCovidMap`
		_, err = templBuffer.WriteString(var_2)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h1><p>")
		if err != nil {
			return err
		}
		var_3 := `Over the course of the pandemic, the NZCovidMap reached over 200,000 Kiwis across New Zealand, with a peak of 15,000 daily unique visitors. This tool provided people with a mobile-friendly view of Covid-19 Locations of Interest published by the Ministry of Health. As locations are found, the application automatically maintained Reddit posts for any new locations in relevant community subreddits. A creative circle-based location selection method allows the user to view the information for many locations in a specific area.`
		_, err = templBuffer.WriteString(var_3)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</p></div><div class=\"flex justify-center\"><img class=\"rounded-lg shadow-lg\" src=\"/_next/image?url=%2Fimg%2Fnzcovidmap%2Fnzcovid_2.jpg&amp;w=640&amp;q=75\" alt=\"NZCovidMap Screenshot\"><!--")
		if err != nil {
			return err
		}
		var_4 := ` Additional images can be added similarly `
		_, err = templBuffer.WriteString(var_4)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("--></div><div class=\"font-bold rounded-lg border shadow-lg p-10\"><h1>")
		if err != nil {
			return err
		}
		var_5 := `The goals were:`
		_, err = templBuffer.WriteString(var_5)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h1><ul class=\"list-inside list-disc\"><li>")
		if err != nil {
			return err
		}
		var_6 := `Provide a Mobile-friendly view of Locations of Interest`
		_, err = templBuffer.WriteString(var_6)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</li><li>")
		if err != nil {
			return err
		}
		var_7 := `Raise awareness of Locations of Interests in our community.`
		_, err = templBuffer.WriteString(var_7)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</li><li>")
		if err != nil {
			return err
		}
		var_8 := `Lower anxiety for those seeking updates about their community.`
		_, err = templBuffer.WriteString(var_8)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</li></ul><h1>")
		if err != nil {
			return err
		}
		var_9 := `Tech`
		_, err = templBuffer.WriteString(var_9)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h1><ul class=\"list-inside list-disc\"><li>")
		if err != nil {
			return err
		}
		var_10 := `A Mobile-friendly map view for digesting localized information`
		_, err = templBuffer.WriteString(var_10)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</li><li>")
		if err != nil {
			return err
		}
		var_11 := `Up-to-date social Media sharing icons created for each town/city`
		_, err = templBuffer.WriteString(var_11)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</li><li>")
		if err != nil {
			return err
		}
		var_12 := `Reddit Integration - Auto-Generate a "Location of Interest summary" for each subreddit & share relevant subreddit`
		_, err = templBuffer.WriteString(var_12)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</li></ul></div><!--")
		if err != nil {
			return err
		}
		var_13 := ` Additional content blocks can be structured similarly `
		_, err = templBuffer.WriteString(var_13)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("--></div></div>")
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}
